name: build-test

on:
  pull_request:
  push:
    paths-ignore: [ "README.md" ]
    branches: [ "main", "releases/*" ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        lazarus-versions: [stable]

    steps:
    - name: Cechout source code
      uses: actions/checkout@v3

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        include-packages: "Jvcllaz, NiceGrid, VirtualTreeViewV5"
        with-cache: false

    - name: Build the Main Application (Windows)
      if: ${{ matrix.operating-system == 'windows-latest' }}
      run: lazbuild -B --bm=Release "src/FluPP.lpi"

    - name: Build the Main Application (Ubuntu)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: |
        echo Building with GTK2
        lazbuild -B --bm=Release "src/FluPP.lpi"
        echo Installing Qt5 Dev
        sudo apt update
        sudo apt install libqt5pas-dev -y
        echo Building with Qt5
        lazbuild -B --bm=Release --ws=qt5 "src/FluPP.lpi"

    - name: Build the Main Application (macOS)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      run: lazbuild -B --bm=Release --ws=cocoa "src/FluPP.lpi"
      
    - name: Artifacts (Linux)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: Compiled Linux Binary
        path: |
          FluPP
    - name: Artifacts (Windows)
      if: ${{ matrix.operating-system == 'windows-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: Compiled Windows Binary
        path: |
          src\lib\x86_64-win64\FluPP.exe
    - name: Artifacts (macOS)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: Compiled Mac OS Binary
        path: |
           FluPP.app